### ISSUE TITLE
YAY!!!

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/m2-evaluacion-intermedia-AlbaGomezPerez#1]
Really cool job @AlbaGomezPerez  !!!

Here you have some tips to improve the exercise:

### JavaScript

- [ ] Remember that every time we use `.innerHTML` or `.value` to get DOM content we receive a string. Sometimes we will need to use something like `parseInt()` to convert it to a number

### Further challenges

Then you can improve the game as you please, here you have some ideas:

- Add new feedback when the number is bigger than 100 or smaller than 0.
- Manage when the user hits the button and the input is empty.
- Make the input work when hitting the enter key.
- Add a reset button that cleans the input, the counter, writes the initial feedback and generates a new random number to play again!
- Whatever you want!

### Call to action

Let me know if you have any doubts ;)

Go for it!!

**Comment by AlbaGomezPerez** [comment]
- [x] Remember that every time we use .innerHTML or .value to get DOM content we receive a string. Sometimes we will need to use something like parseInt() to convert it to a number 02ca0fac75d968adc1f56ea59cf9de640151e332
- [x] Add new feedback when the number is bigger than 100 or smaller than 0. 20e6f49863042ee4f0bb557ab6c314903a41fb31 8a78502a03950fded9e6866c290ed785e5d20a71
- [x] Manage when the user hits the button and the input is empty. aa8dd0aba9ff0e2b532b16671d6e68ba2b126ad7
- [x] Make the input work when hitting the enter key. 1d07d8bf2c9b49dbe9fe85389fc2007b664e8e8b
- [x] Add a reset button that cleans the input, the counter, writes the initial feedback and generates a new random number to play again! 6c08d2bdf1f3dcaa4e27da8509e5e3e1b5d596c5
